import { LifecycleStage, User } from '@/types';

export const LIFECYCLE_STAGES: LifecycleStage[] = [
  { key: 'manpower_planning', label: 'Manpower Planning', order: 1, description: 'Plant workforce requisition & budget approval' },
  { key: 'recruitment', label: 'Recruitment', order: 2, description: 'Sourcing, screening & technical interview rounds' },
  { key: 'selection', label: 'Selection', order: 3, description: 'Technical scorecard & candidate selection' },
  { key: 'offer', label: 'Offer & Pre-Joining', order: 4, description: 'Offer letter rollout & credential verification' },
  { key: 'joining', label: 'Joining & Day 1', order: 5, description: 'Plant safety kit, ID issuance & workstation setup' },
  { key: 'onboarding', label: 'Onboarding & KRAs', order: 6, description: 'EHS signoff, supervisor buddy & operational goals' },
  { key: 'attendance_leave', label: 'Attendance & Leave', order: 7, description: 'Shift biometric capture & statutory leave records' },
  { key: 'payroll', label: 'Payroll & Benefits', order: 8, description: 'Monthly wage processing & PF/ESI/PT statutory filing' },
  { key: 'performance', label: 'Performance Appraisal', order: 9, description: 'Plant KRA review & annual calibration' },
  { key: 'training', label: 'Training & Skill Dev', order: 10, description: 'Industrial safety, ISO 9001 & technical upskilling' },
  { key: 'engagement', label: 'Engagement & Welfare', order: 11, description: 'Plant committee, surveys & grievance resolution' },
  { key: 'transfer_promotion', label: 'Transfer & Promotion', order: 12, description: 'Inter-plant transfers, grade upgrades & promotions' },
  { key: 'compliance', label: 'Policy & Compliance', order: 13, description: 'Factory Act registers, EHS audits & inspections' },
  { key: 'resignation', label: 'Resignation Notice', order: 14, description: 'Resignation submission & notice period calculation' },
  { key: 'clearance', label: 'Department Clearance', order: 15, description: 'Plant tools, IT, Finance, & HR digital sign-offs' },
  { key: 'ff_settlement', label: 'Full & Final (F&F)', order: 16, description: 'Final dues, leave encashment & gratuity clearance' },
  { key: 'exit_documentation', label: 'Exit & Archival', order: 17, description: 'Relieving certificate & permanent statutory archival' },
];

export const CORE_PERSONAS: User[] = [
  {
    id: 'usr_chairman',
    name: 'Alexander Sterling',
    email: 'alexander.sterling@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Alexander+Sterling&background=4f46e5&color=ffffff',
    roles: ['chairman'],
    activeRole: 'chairman',
    status: 'active',
    lastLogin: '2026-08-14T08:45:00Z',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'usr_md',
    name: 'Dr. Vikramaditya Rathore',
    email: 'vikram.rathore@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Vikramaditya+Rathore&background=4f46e5&color=ffffff',
    roles: ['managing_director'],
    activeRole: 'managing_director',
    employeeId: 'emp_004',
    departmentId: 'dept_qc',
    status: 'active',
    lastLogin: '2026-08-14T08:00:00Z',
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'usr_hr_head',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Eleanor+Vance&background=4f46e5&color=ffffff',
    roles: ['hr_head'],
    activeRole: 'hr_head',
    employeeId: 'emp_001',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-14T09:12:00Z',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'usr_internal_audit',
    name: 'Marcus Chen',
    email: 'marcus.chen@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Marcus+Chen&background=4f46e5&color=ffffff',
    roles: ['internal_audit_head'],
    activeRole: 'internal_audit_head',
    employeeId: 'emp_003',
    departmentId: 'dept_fin',
    status: 'active',
    lastLogin: '2026-08-14T06:00:00Z',
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'usr_compliance',
    name: 'Rajeshwari Nair',
    email: 'rajeshwari.nair@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Rajeshwari+Nair&background=4f46e5&color=ffffff',
    roles: ['compliance_statutory'],
    activeRole: 'compliance_statutory',
    employeeId: 'emp_002',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-14T07:30:00Z',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'usr_employee',
    name: 'Vishwadharan R',
    email: 'vishwadharan.r@viruzverse.com',
    avatar: 'https://ui-avatars.com/api/?name=Vishwadharan+R&background=4f46e5&color=ffffff',
    roles: ['employee'],
    activeRole: 'employee',
    employeeId: 'emp_005',
    departmentId: 'dept_qc',
    status: 'active',
    lastLogin: '2026-08-14T08:30:00Z',
    createdAt: '2025-01-15T00:00:00Z',
  },
];

export function getPersonaAvatar(codeOrEmail?: string, fallbackName?: string): string {
  const name = (fallbackName || codeOrEmail || 'User').trim();
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=4f46e5&color=ffffff`;
}
