import {
  User,
  Department,
  Designation,
  Branch,
  Employee,
  AttendanceRecord,
  LeaveRequest,
  LeaveBalance,
  PayrollRun,
  Payslip,
  Candidate,
  ManpowerRequisition,
  PerformanceCycle,
  PerformanceReview,
  GrievanceTicket,
  TrainingProgram,
  PolicyDocument,
  ResignationCase,
  DisciplinaryCase,
  TransferPromotionCase,
  AuditLogItem,
  SystemNotification,
  LifecycleStage,
} from '@/types';
import { calculateSalaryBreakup } from '@/lib/utils';

export const LIFECYCLE_STAGES: LifecycleStage[] = [
  { key: 'manpower_planning', label: 'Manpower Planning', order: 1, description: 'Workforce requisition & budget approval' },
  { key: 'recruitment', label: 'Recruitment', order: 2, description: 'Sourcing, screening & interview rounds' },
  { key: 'selection', label: 'Selection', order: 3, description: 'Interviewer scorecard & candidate selection' },
  { key: 'offer', label: 'Offer & Pre-Joining', order: 4, description: 'Offer letter rollout & doc verification' },
  { key: 'joining', label: 'Joining & Day 1', order: 5, description: 'Welcome kit, ID issuance & IT assets' },
  { key: 'onboarding', label: 'Onboarding & KRAs', order: 6, description: 'Policy signoffs, buddy & initial goals' },
  { key: 'attendance_leave', label: 'Attendance & Leave', order: 7, description: 'Daily logging & leave policy management' },
  { key: 'payroll', label: 'Payroll & Benefits', order: 8, description: 'Monthly salary disbursement & statutory compliance' },
  { key: 'performance', label: 'Performance Appraisal', order: 9, description: 'Continuous check-ins & appraisal cycles' },
  { key: 'training', label: 'Training & Skill Dev', order: 10, description: 'Upskilling programs & certification logs' },
  { key: 'engagement', label: 'Engagement & Welfare', order: 11, description: 'Surveys, events, and grievance handling' },
  { key: 'transfer_promotion', label: 'Transfer & Promotion', order: 12, description: 'Role upgrades, grade changes & lateral moves' },
  { key: 'compliance', label: 'Policy & Compliance', order: 13, description: 'Labor audits, statutory registers & renewals' },
  { key: 'resignation', label: 'Resignation Notice', order: 14, description: 'Resignation submission & notice period calculation' },
  { key: 'clearance', label: 'Department Clearance', order: 15, description: 'IT, Admin, Finance, & HR digital sign-offs' },
  { key: 'ff_settlement', label: 'Full & Final (F&F)', order: 16, description: 'Final dues, leave encashment & tax clearance' },
  { key: 'exit_documentation', label: 'Exit & Archival', order: 17, description: 'Relieving letter & permanent record archival' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'usr_super_admin',
    name: 'Alexander Sterling',
    email: 'alexander.sterling@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    roles: ['super_admin'],
    activeRole: 'super_admin',
    status: 'active',
    lastLogin: '2026-08-13T18:45:00Z',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'usr_hr_admin',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    roles: ['hr_admin', 'reporting_manager'],
    activeRole: 'hr_admin',
    employeeId: 'emp_001',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-13T19:12:00Z',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'usr_hr_exec',
    name: 'Priya Sharma',
    email: 'priya.sharma@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    roles: ['hr_executive'],
    activeRole: 'hr_executive',
    employeeId: 'emp_002',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-13T17:30:00Z',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'usr_payroll',
    name: 'Marcus Chen',
    email: 'marcus.chen@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    roles: ['payroll_officer'],
    activeRole: 'payroll_officer',
    employeeId: 'emp_003',
    departmentId: 'dept_fin',
    status: 'active',
    lastLogin: '2026-08-13T16:00:00Z',
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'usr_manager',
    name: 'Dr. Vikramaditya Rathore',
    email: 'vikram.rathore@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    roles: ['reporting_manager', 'employee'],
    activeRole: 'reporting_manager',
    employeeId: 'emp_004',
    departmentId: 'dept_eng',
    status: 'active',
    lastLogin: '2026-08-13T18:00:00Z',
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'usr_employee',
    name: 'Ananya Deshmukh',
    email: 'ananya.deshmukh@viruzverse.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    roles: ['employee'],
    activeRole: 'employee',
    employeeId: 'emp_005',
    departmentId: 'dept_eng',
    status: 'active',
    lastLogin: '2026-08-13T19:25:00Z',
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dept_hr', name: 'Human Resources & People Ops', code: 'HRPO', headId: 'emp_001', headName: 'Eleanor Vance', employeeCount: 8 },
  { id: 'dept_eng', name: 'Software Engineering & AI', code: 'SEAI', headId: 'emp_004', headName: 'Dr. Vikramaditya Rathore', employeeCount: 42 },
  { id: 'dept_fin', name: 'Finance & Accounts', code: 'FIN', headId: 'emp_003', headName: 'Marcus Chen', employeeCount: 12 },
  { id: 'dept_sales', name: 'Global Sales & Enterprise', code: 'GSE', headName: 'Rohan Mehra', employeeCount: 25 },
  { id: 'dept_ops', name: 'Operations & Facilities', code: 'OPS', headName: 'Sarah Jenkins', employeeCount: 15 },
];

export const MOCK_DESIGNATIONS: Designation[] = [
  { id: 'des_hr_dir', title: 'VP of People & Culture', departmentId: 'dept_hr', grade: 'E7', level: 7 },
  { id: 'des_hr_exec', title: 'HR Operations Executive', departmentId: 'dept_hr', grade: 'E3', level: 3 },
  { id: 'des_fin_lead', title: 'Principal Payroll & Tax Specialist', departmentId: 'dept_fin', grade: 'E5', level: 5 },
  { id: 'des_eng_dir', title: 'VP of Engineering', departmentId: 'dept_eng', grade: 'E8', level: 8 },
  { id: 'des_sr_dev', title: 'Senior Full Stack Engineer', departmentId: 'dept_eng', grade: 'E4', level: 4 },
  { id: 'des_dev', title: 'Software Engineer II', departmentId: 'dept_eng', grade: 'E3', level: 3 },
  { id: 'des_qa_lead', title: 'Lead QA Automation Engineer', departmentId: 'dept_eng', grade: 'E4', level: 4 },
];

export const MOCK_BRANCHES: Branch[] = [
  { id: 'br_blr', name: 'Bengaluru Tech Park Campus', city: 'Bengaluru', country: 'India', isHeadquarters: true },
  { id: 'br_hyd', name: 'Hyderabad Cyber City Center', city: 'Hyderabad', country: 'India', isHeadquarters: false },
  { id: 'br_mum', name: 'Mumbai Financial District', city: 'Mumbai', country: 'India', isHeadquarters: false },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp_001',
    userId: 'usr_hr_admin',
    employeeCode: 'VV-1001',
    firstName: 'Eleanor',
    lastName: 'Vance',
    email: 'eleanor.vance@viruzverse.com',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1988-04-12',
    dateOfJoining: '2021-03-15',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & People Ops',
    designationId: 'des_hr_dir',
    designationTitle: 'VP of People & Culture',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'active',
    currentLifecycleStage: 'compliance',
    ctc: 3200000,
    bankDetails: {
      accountNumber: '•••• •••• 9821',
      bankName: 'HDFC Bank Ltd',
      ifscCode: 'HDFC0001234',
      pan: 'ABCDE1234F',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1001',
      esiNumber: '53-00-123456-000-0001',
      uan: '100987654321',
    },
    emergencyContact: {
      name: 'Robert Vance',
      relationship: 'Spouse',
      phone: '+91 98765 43219',
    },
  },
  {
    id: 'emp_002',
    userId: 'usr_hr_exec',
    employeeCode: 'VV-1002',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@viruzverse.com',
    phone: '+91 98765 43211',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1995-09-24',
    dateOfJoining: '2023-06-01',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & People Ops',
    designationId: 'des_hr_exec',
    designationTitle: 'HR Operations Executive',
    reportingManagerId: 'emp_001',
    reportingManagerName: 'Eleanor Vance',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'active',
    currentLifecycleStage: 'training',
    ctc: 950000,
    bankDetails: {
      accountNumber: '•••• •••• 4412',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000987',
      pan: 'FGHIJ5678K',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1002',
      uan: '100987654322',
    },
    emergencyContact: {
      name: 'Rajesh Sharma',
      relationship: 'Father',
      phone: '+91 98765 43220',
    },
  },
  {
    id: 'emp_003',
    userId: 'usr_payroll',
    employeeCode: 'VV-1003',
    firstName: 'Marcus',
    lastName: 'Chen',
    email: 'marcus.chen@viruzverse.com',
    phone: '+91 98765 43212',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1990-11-05',
    dateOfJoining: '2022-01-10',
    departmentId: 'dept_fin',
    departmentName: 'Finance & Accounts',
    designationId: 'des_fin_lead',
    designationTitle: 'Principal Payroll & Tax Specialist',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'active',
    currentLifecycleStage: 'payroll',
    ctc: 2100000,
    bankDetails: {
      accountNumber: '•••• •••• 8820',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0000543',
      pan: 'KLMNO9012P',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1003',
      uan: '100987654323',
    },
    emergencyContact: {
      name: 'Linda Chen',
      relationship: 'Spouse',
      phone: '+91 98765 43221',
    },
  },
  {
    id: 'emp_004',
    userId: 'usr_manager',
    employeeCode: 'VV-1004',
    firstName: 'Dr. Vikramaditya',
    lastName: 'Rathore',
    email: 'vikram.rathore@viruzverse.com',
    phone: '+91 98765 43213',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1984-02-18',
    dateOfJoining: '2020-08-01',
    departmentId: 'dept_eng',
    departmentName: 'Software Engineering & AI',
    designationId: 'des_eng_dir',
    designationTitle: 'VP of Engineering',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'active',
    currentLifecycleStage: 'performance',
    ctc: 4800000,
    bankDetails: {
      accountNumber: '•••• •••• 1109',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0004567',
      pan: 'PQRST3456U',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1004',
      uan: '100987654324',
    },
    emergencyContact: {
      name: 'Sunita Rathore',
      relationship: 'Spouse',
      phone: '+91 98765 43222',
    },
  },
  {
    id: 'emp_005',
    userId: 'usr_employee',
    employeeCode: 'VV-1005',
    firstName: 'Ananya',
    lastName: 'Deshmukh',
    email: 'ananya.deshmukh@viruzverse.com',
    phone: '+91 98765 43214',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1998-07-30',
    dateOfJoining: '2024-02-15',
    departmentId: 'dept_eng',
    departmentName: 'Software Engineering & AI',
    designationId: 'des_sr_dev',
    designationTitle: 'Senior Full Stack Engineer',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'active',
    currentLifecycleStage: 'performance',
    ctc: 1850000,
    bankDetails: {
      accountNumber: '•••• •••• 6534',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0001122',
      pan: 'UVWXY7890Z',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1005',
      uan: '100987654325',
    },
    emergencyContact: {
      name: 'Sanjay Deshmukh',
      relationship: 'Father',
      phone: '+91 98765 43223',
    },
  },
  {
    id: 'emp_006',
    userId: 'usr_emp_006',
    employeeCode: 'VV-1006',
    firstName: 'Karthik',
    lastName: 'Subramanian',
    email: 'karthik.s@viruzverse.com',
    phone: '+91 98765 43215',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1996-03-14',
    dateOfJoining: '2024-06-10',
    departmentId: 'dept_eng',
    departmentName: 'Software Engineering & AI',
    designationId: 'des_dev',
    designationTitle: 'Software Engineer II',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_hyd',
    branchName: 'Hyderabad Cyber City Center',
    employmentStatus: 'probation',
    currentLifecycleStage: 'onboarding',
    ctc: 1200000,
    bankDetails: {
      accountNumber: '•••• •••• 7712',
      bankName: 'HDFC Bank Ltd',
      ifscCode: 'HDFC0004455',
      pan: 'ZXCVB1234Q',
    },
    statutory: {
      pfNumber: 'TS/HYD/0098765/000/1006',
      uan: '100987654326',
    },
    emergencyContact: {
      name: 'Meena Subramanian',
      relationship: 'Mother',
      phone: '+91 98765 43224',
    },
  },
  {
    id: 'emp_007',
    userId: 'usr_emp_007',
    employeeCode: 'VV-1007',
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    email: 'sneha.k@viruzverse.com',
    phone: '+91 98765 43216',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1993-12-08',
    dateOfJoining: '2023-01-15',
    departmentId: 'dept_eng',
    departmentName: 'Software Engineering & AI',
    designationId: 'des_qa_lead',
    designationTitle: 'Lead QA Automation Engineer',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_blr',
    branchName: 'Bengaluru Tech Park Campus',
    employmentStatus: 'notice_period',
    currentLifecycleStage: 'resignation',
    ctc: 1650000,
    bankDetails: {
      accountNumber: '•••• •••• 9931',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001928',
      pan: 'ASDFG5678H',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1007',
      uan: '100987654327',
    },
    emergencyContact: {
      name: 'Amit Kulkarni',
      relationship: 'Spouse',
      phone: '+91 98765 43225',
    },
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att_1', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-13', inTime: '09:12 AM', outTime: '06:35 PM', totalHours: 9.38, status: 'present', source: 'biometric' },
  { id: 'att_2', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-12', inTime: '09:05 AM', outTime: '06:15 PM', totalHours: 9.16, status: 'present', source: 'biometric' },
  { id: 'att_3', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-11', inTime: '10:15 AM', outTime: '06:45 PM', totalHours: 8.50, status: 'present', source: 'manual', regularizationStatus: 'approved', regularizationReason: 'Traffic due to metro construction' },
  { id: 'att_4', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-10', inTime: '09:30 AM', outTime: '02:00 PM', totalHours: 4.50, status: 'half_day', source: 'web_checkin' },
  { id: 'att_5', employeeId: 'emp_006', employeeName: 'Karthik Subramanian', date: '2026-08-13', inTime: '08:58 AM', outTime: '05:55 PM', totalHours: 8.95, status: 'present', source: 'biometric' },
  { id: 'att_6', employeeId: 'emp_007', employeeName: 'Sneha Kulkarni', date: '2026-08-13', inTime: '09:45 AM', outTime: '06:40 PM', totalHours: 8.91, status: 'present', source: 'biometric' },
  { id: 'att_7', employeeId: 'emp_002', employeeName: 'Priya Sharma', date: '2026-08-13', inTime: '09:00 AM', outTime: '06:00 PM', totalHours: 9.00, status: 'present', source: 'biometric' },
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr_101',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    leaveType: 'casual',
    fromDate: '2026-08-20',
    toDate: '2026-08-21',
    daysCount: 2,
    reason: 'Family wedding ceremony out of town',
    status: 'pending',
    approverId: 'emp_004',
    approverName: 'Dr. Vikramaditya Rathore',
    appliedAt: '2026-08-12T14:30:00Z',
  },
  {
    id: 'lr_102',
    employeeId: 'emp_006',
    employeeName: 'Karthik Subramanian',
    leaveType: 'sick',
    fromDate: '2026-08-05',
    toDate: '2026-08-05',
    daysCount: 1,
    reason: 'Viral fever & medical checkup',
    status: 'approved',
    approverId: 'emp_004',
    approverName: 'Dr. Vikramaditya Rathore',
    appliedAt: '2026-08-04T20:15:00Z',
    approverComment: 'Approved. Get well soon!',
  },
  {
    id: 'lr_103',
    employeeId: 'emp_002',
    employeeName: 'Priya Sharma',
    leaveType: 'earned',
    fromDate: '2026-09-01',
    toDate: '2026-09-05',
    daysCount: 5,
    reason: 'Annual vacation with family',
    status: 'approved',
    approverId: 'emp_001',
    approverName: 'Eleanor Vance',
    appliedAt: '2026-08-10T10:00:00Z',
    approverComment: 'Approved. Enjoy your break!',
  },
];

export const MOCK_LEAVE_BALANCES: LeaveBalance[] = [
  { employeeId: 'emp_005', leaveType: 'casual', totalAllocated: 12, used: 3, pending: 2, balance: 7 },
  { employeeId: 'emp_005', leaveType: 'sick', totalAllocated: 10, used: 2, pending: 0, balance: 8 },
  { employeeId: 'emp_005', leaveType: 'earned', totalAllocated: 15, used: 4, pending: 0, balance: 11 },
  { employeeId: 'emp_005', leaveType: 'maternity', totalAllocated: 180, used: 0, pending: 0, balance: 180 },
];

export const MOCK_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: 'pr_2026_07',
    period: '2026-07',
    monthName: 'July',
    year: 2026,
    status: 'disbursed',
    totalEmployees: 102,
    totalGrossPay: 8645000,
    totalDeductions: 1234000,
    totalNetPay: 7411000,
    varianceCount: 0,
    runDate: '2026-07-31T18:00:00Z',
    approvedBy: 'Eleanor Vance',
    approvedAt: '2026-07-31T17:30:00Z',
  },
  {
    id: 'pr_2026_08',
    period: '2026-08',
    monthName: 'August',
    year: 2026,
    status: 'under_review',
    totalEmployees: 105,
    totalGrossPay: 8910000,
    totalDeductions: 1285000,
    totalNetPay: 7625000,
    varianceCount: 3,
    runDate: '2026-08-13T12:00:00Z',
  },
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'ps_2026_07_005',
    payrollRunId: 'pr_2026_07',
    employeeId: 'emp_005',
    employeeCode: 'VV-1005',
    employeeName: 'Ananya Deshmukh',
    designation: 'Senior Full Stack Engineer',
    department: 'Software Engineering & AI',
    period: 'July 2026',
    paidDays: 31,
    lopDays: 0,
    breakup: calculateSalaryBreakup(1850000),
    paymentMode: 'bank_transfer',
    status: 'published',
  },
  {
    id: 'ps_2026_07_006',
    payrollRunId: 'pr_2026_07',
    employeeId: 'emp_006',
    employeeCode: 'VV-1006',
    employeeName: 'Karthik Subramanian',
    designation: 'Software Engineer II',
    department: 'Software Engineering & AI',
    period: 'July 2026',
    paidDays: 31,
    lopDays: 0,
    breakup: calculateSalaryBreakup(1200000),
    paymentMode: 'bank_transfer',
    status: 'published',
  },
];

export const MOCK_REQUISITIONS: ManpowerRequisition[] = [
  {
    id: 'req_001',
    departmentId: 'dept_eng',
    departmentName: 'Software Engineering & AI',
    positionTitle: 'Staff Backend Architect (Go/Rust/Cloud)',
    openingsCount: 2,
    urgency: 'high',
    requestedById: 'emp_004',
    requestedByName: 'Dr. Vikramaditya Rathore',
    status: 'approved',
    targetDate: '2026-09-30',
    minExperience: '8+ Years',
    justification: 'Scaling distributed enterprise multi-tenant core services for global clients.',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'req_002',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & People Ops',
    positionTitle: 'Senior Talent Acquisition Lead',
    openingsCount: 1,
    urgency: 'medium',
    requestedById: 'emp_001',
    requestedByName: 'Eleanor Vance',
    status: 'in_progress',
    targetDate: '2026-09-15',
    minExperience: '5+ Years',
    justification: 'Accelerating tech and product hiring for Q3 and Q4 expansions.',
    createdAt: '2026-08-05T11:00:00Z',
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand_01',
    requisitionId: 'req_001',
    name: 'Devraj Mukherjee',
    email: 'devraj.mukherjee@example.com',
    phone: '+91 98111 22334',
    position: 'Staff Backend Architect',
    department: 'Software Engineering & AI',
    experienceYears: 9,
    currentStage: 'interview',
    score: 92,
    interviewDate: '2026-08-14T11:00:00Z',
    interviewerId: 'emp_004',
    interviewerName: 'Dr. Vikramaditya Rathore',
    interviewerScorecard: {
      technicalRating: 4.8,
      cultureRating: 4.5,
      communicationRating: 4.6,
      comments: 'Exceptional deep knowledge in distributed systems, PostgreSQL query planners, and microservices.',
      recommendation: 'hire',
    },
  },
  {
    id: 'cand_02',
    requisitionId: 'req_001',
    name: 'Shreya Sengupta',
    email: 'shreya.sengupta@example.com',
    phone: '+91 98222 33445',
    position: 'Staff Backend Architect',
    department: 'Software Engineering & AI',
    experienceYears: 8,
    currentStage: 'offered',
    score: 89,
    offerDetails: {
      offeredCtc: 3800000,
      joiningDate: '2026-09-15',
      status: 'sent',
    },
  },
  {
    id: 'cand_03',
    requisitionId: 'req_001',
    name: 'Nikhil Verma',
    email: 'nikhil.verma@example.com',
    phone: '+91 98333 44556',
    position: 'Staff Backend Architect',
    department: 'Software Engineering & AI',
    experienceYears: 7,
    currentStage: 'screened',
    score: 84,
  },
  {
    id: 'cand_04',
    requisitionId: 'req_001',
    name: 'Aarav Patel',
    email: 'aarav.patel@example.com',
    phone: '+91 98444 55667',
    position: 'Staff Backend Architect',
    department: 'Software Engineering & AI',
    experienceYears: 5,
    currentStage: 'applied',
    score: 76,
  },
];

export const MOCK_PERFORMANCE_CYCLES: PerformanceCycle[] = [
  {
    id: 'pc_2025_26',
    title: 'Annual Performance Appraisal 2025-2026',
    period: 'FY 2025-2026',
    status: 'calibration',
    deadline: '2026-08-30',
    totalEligible: 98,
    submittedCount: 94,
    reviewedCount: 88,
  },
];

export const MOCK_PERFORMANCE_REVIEWS: PerformanceReview[] = [
  {
    id: 'pr_rev_005',
    cycleId: 'pc_2025_26',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    department: 'Software Engineering & AI',
    designation: 'Senior Full Stack Engineer',
    kras: [
      { title: 'Core Architecture & Code Quality', weightage: 35, target: 'Deliver modular, clean code with 90%+ unit test coverage', selfScore: 4.8, managerScore: 4.7 },
      { title: 'Platform Performance & Latency', weightage: 30, target: 'Optimize API response times under 120ms at p99', selfScore: 4.5, managerScore: 4.6 },
      { title: 'Mentorship & Knowledge Transfer', weightage: 20, target: 'Mentor 2 junior engineers through onboarding and PR reviews', selfScore: 4.5, managerScore: 4.5 },
      { title: 'Security & Compliance Audits', weightage: 15, target: 'Zero vulnerability findings in quarterly pen tests', selfScore: 5.0, managerScore: 4.9 },
    ],
    selfRating: 4.7,
    managerRating: 4.68,
    finalRating: 4.7,
    managerComments: 'Ananya has consistently exceeded expectations, demonstrating exceptional ownership across our core modules.',
    hrCalibrationNotes: 'Top 5% performer across engineering. Recommended for Lead promotion & 18% merit increment.',
    recommendation: 'promotion',
    status: 'in_calibration',
  },
];

export const MOCK_GRIEVANCES: GrievanceTicket[] = [
  {
    id: 'grv_01',
    ticketNumber: 'GRV-2026-0042',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    isAnonymous: false,
    category: 'work_environment',
    subject: 'Ergonomic seating upgrade request for 3rd floor wing',
    description: 'Multiple team members experiencing discomfort due to aging chair lumbar supports in block B.',
    priority: 'medium',
    status: 'under_investigation',
    slaDeadline: '2026-08-18T18:00:00Z',
    assignedToName: 'Sarah Jenkins (Ops)',
    createdAt: '2026-08-11T10:00:00Z',
  },
  {
    id: 'grv_02',
    ticketNumber: 'GRV-2026-0043',
    isAnonymous: true,
    category: 'policy_violation',
    subject: 'Shift timing discrepancy notification',
    description: 'Inquiry regarding weekend overtime rate calculation for production support shifts.',
    priority: 'high',
    status: 'resolved',
    slaDeadline: '2026-08-14T18:00:00Z',
    assignedToName: 'Eleanor Vance (HR)',
    resolutionNotes: 'Clarified overtime slab computation rules and credited retroactive allowance in July payroll.',
    createdAt: '2026-08-08T15:30:00Z',
  },
];

export const MOCK_TRAININGS: TrainingProgram[] = [
  {
    id: 'trn_01',
    title: 'Advanced Cloud Architecture & Kubernetes Security',
    trainer: 'CloudSec Global Labs (External)',
    category: 'technical',
    startDate: '2026-08-22',
    endDate: '2026-08-24',
    mode: 'external_vendor',
    vendorName: 'CloudSec Global Labs Inc.',
    capacity: 25,
    enrolledCount: 22,
    status: 'upcoming',
  },
  {
    id: 'trn_02',
    title: 'POSH & Workplace Ethics Compliance Workshop 2026',
    trainer: 'Eleanor Vance & Legal Counsel',
    category: 'compliance',
    startDate: '2026-08-10',
    endDate: '2026-08-10',
    mode: 'internal',
    capacity: 120,
    enrolledCount: 114,
    status: 'completed',
    feedbackAvgScore: 4.85,
  },
];

export const MOCK_POLICIES: PolicyDocument[] = [
  {
    id: 'pol_01',
    title: 'Code of Business Conduct & Ethics 2026',
    category: 'code_of_conduct',
    version: 'v3.2',
    effectiveDate: '2026-01-01',
    acknowledgedCount: 98,
    totalEmployees: 105,
    fileUrl: '/policies/code-of-conduct-v3.2.pdf',
  },
  {
    id: 'pol_02',
    title: 'Prevention of Sexual Harassment (POSH) Policy',
    category: 'posh',
    version: 'v4.0',
    effectiveDate: '2026-01-01',
    acknowledgedCount: 105,
    totalEmployees: 105,
    fileUrl: '/policies/posh-policy-v4.0.pdf',
  },
  {
    id: 'pol_03',
    title: 'Global Information Security & Clean Desk Policy',
    category: 'it_security',
    version: 'v2.1',
    effectiveDate: '2026-03-01',
    acknowledgedCount: 101,
    totalEmployees: 105,
    fileUrl: '/policies/infosec-policy-v2.1.pdf',
  },
];

export const MOCK_RESIGNATIONS: ResignationCase[] = [
  {
    id: 'res_001',
    employeeId: 'emp_007',
    employeeName: 'Sneha Kulkarni',
    resignationDate: '2026-07-20',
    requestedLwd: '2026-08-20',
    approvedLwd: '2026-08-20',
    noticePeriodDays: 30,
    reason: 'Pursuing higher studies (Master of Science abroad)',
    status: 'clearance_in_progress',
    clearances: {
      it: { status: 'cleared', clearedBy: 'IT Asset Team', notes: 'MacBook Pro, Monitor & Access badge returned.' },
      admin: { status: 'cleared', clearedBy: 'Admin Ops', notes: 'No pending locker or library items.' },
      finance: { status: 'pending', notes: 'Final travel reimbursement verification under review.' },
      hr: { status: 'pending', notes: 'Exit interview scheduled for Aug 18.' },
    },
    ffSettlement: {
      pendingSalary: 106450,
      leaveEncashment: 42500,
      bonusGratuity: 0,
      noticeShortfallDeduction: 0,
      assetDeduction: 0,
      totalNetSettlement: 148950,
      status: 'draft',
    },
  },
];

export const MOCK_DISCIPLINARY: DisciplinaryCase[] = [
  {
    id: 'disc_01',
    caseNumber: 'DISC-2026-003',
    employeeId: 'emp_006',
    employeeName: 'Karthik Subramanian',
    violationType: 'absenteeism',
    incidentDate: '2026-07-15',
    reportedBy: 'Dr. Vikramaditya Rathore',
    severity: 'minor',
    currentStage: 'capa_active',
    actionTaken: 'written_warning',
    createdAt: '2026-07-16T14:00:00Z',
  },
];

export const MOCK_TRANSFERS: TransferPromotionCase[] = [
  {
    id: 'tp_01',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    type: 'promotion',
    currentDepartment: 'Software Engineering & AI',
    newDepartment: 'Software Engineering & AI',
    currentDesignation: 'Senior Full Stack Engineer',
    newDesignation: 'Lead Full Stack Architect',
    currentBranch: 'Bengaluru Tech Park Campus',
    newBranch: 'Bengaluru Tech Park Campus',
    effectiveDate: '2026-09-01',
    initiatedBy: 'Dr. Vikramaditya Rathore',
    status: 'pending_approval',
    approvalChain: ['Dr. Vikramaditya Rathore (Manager)', 'Eleanor Vance (HR Head)'],
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  { id: 'aud_1', userId: 'usr_hr_admin', userName: 'Eleanor Vance', role: 'hr_admin', action: 'APPROVED_REQUISITION', module: 'recruitment', entityId: 'req_001', details: 'Approved Staff Backend Architect headcount for Engineering', timestamp: '2026-08-13T18:40:12Z', ipAddress: '10.0.4.18' },
  { id: 'aud_2', userId: 'usr_payroll', userName: 'Marcus Chen', role: 'payroll_officer', action: 'INITIATED_PAYROLL_RUN', module: 'payroll_benefits', entityId: 'pr_2026_08', details: 'Computed August 2026 payroll input sheet for 105 employees', timestamp: '2026-08-13T12:00:00Z', ipAddress: '10.0.2.44' },
  { id: 'aud_3', userId: 'usr_manager', userName: 'Dr. Vikramaditya Rathore', role: 'reporting_manager', action: 'SUBMITTED_SCORECARD', module: 'recruitment', entityId: 'cand_01', details: 'Submitted 4.8/5.0 interview scorecard for Devraj Mukherjee', timestamp: '2026-08-12T16:15:30Z', ipAddress: '10.0.1.92' },
  { id: 'aud_4', userId: 'usr_super_admin', userName: 'Alexander Sterling', role: 'super_admin', action: 'UPDATED_SECURITY_POLICY', module: 'system_settings', entityId: 'sec_01', details: 'Enforced 90-day mandatory password rotation & MFA', timestamp: '2026-08-10T11:00:00Z', ipAddress: '10.0.0.1' },
];

export const MOCK_NOTIFICATIONS: SystemNotification[] = [
  { id: 'notif_1', title: 'New Leave Request', message: 'Ananya Deshmukh applied for 2 days Casual Leave (20-21 Aug)', type: 'info', module: 'attendance_leave', createdAt: '2026-08-12T14:30:00Z', read: false, link: '/leaves' },
  { id: 'notif_2', title: 'August Payroll Review', message: 'August 2026 Payroll Run is ready for HR Admin approval', type: 'warning', module: 'payroll_benefits', createdAt: '2026-08-13T12:05:00Z', read: false, link: '/payroll' },
  { id: 'notif_3', title: 'Candidate Scorecard', message: 'Scorecard submitted for Devraj Mukherjee (Staff Architect)', type: 'success', module: 'recruitment', createdAt: '2026-08-12T16:20:00Z', read: true, link: '/recruitment' },
  { id: 'notif_4', title: 'Document Expiry Warning', message: 'Sneha Kulkarni work certification expires in 15 days', type: 'alert', module: 'employee_records', createdAt: '2026-08-11T09:00:00Z', read: false, link: '/employees/emp_007' },
];
