import {
  User,
  Department,
  Designation,
  Branch,
  Employee,
  AttendanceRecord,
  LeaveRequest,
  LeaveBalance,
  PayrollRun,
  Payslip,
  Candidate,
  ManpowerRequisition,
  PerformanceCycle,
  PerformanceReview,
  GrievanceTicket,
  TrainingProgram,
  PolicyDocument,
  ResignationCase,
  DisciplinaryCase,
  TransferPromotionCase,
  AuditLogItem,
  SystemNotification,
  LifecycleStage,
} from '@/types';
import { calculateSalaryBreakup } from '@/lib/utils';

export const LIFECYCLE_STAGES: LifecycleStage[] = [
  { key: 'manpower_planning', label: 'Manpower Planning', order: 1, description: 'Plant workforce requisition & budget approval' },
  { key: 'recruitment', label: 'Recruitment', order: 2, description: 'Sourcing, screening & technical interview rounds' },
  { key: 'selection', label: 'Selection', order: 3, description: 'Technical scorecard & candidate selection' },
  { key: 'offer', label: 'Offer & Pre-Joining', order: 4, description: 'Offer letter rollout & credential verification' },
  { key: 'joining', label: 'Joining & Day 1', order: 5, description: 'Plant safety kit, ID issuance & workstation setup' },
  { key: 'onboarding', label: 'Onboarding & KRAs', order: 6, description: 'EHS signoff, supervisor buddy & operational goals' },
  { key: 'attendance_leave', label: 'Attendance & Leave', order: 7, description: 'Shift biometric capture & statutory leave records' },
  { key: 'payroll', label: 'Payroll & Benefits', order: 8, description: 'Monthly wage processing & PF/ESI/PT statutory filing' },
  { key: 'performance', label: 'Performance Appraisal', order: 9, description: 'Plant KRA review & annual calibration' },
  { key: 'training', label: 'Training & Skill Dev', order: 10, description: 'Industrial safety, ISO 9001 & technical upskilling' },
  { key: 'engagement', label: 'Engagement & Welfare', order: 11, description: 'Plant committee, surveys & grievance resolution' },
  { key: 'transfer_promotion', label: 'Transfer & Promotion', order: 12, description: 'Inter-plant transfers, grade upgrades & promotions' },
  { key: 'compliance', label: 'Policy & Compliance', order: 13, description: 'Factory Act registers, EHS audits & inspections' },
  { key: 'resignation', label: 'Resignation Notice', order: 14, description: 'Resignation submission & notice period calculation' },
  { key: 'clearance', label: 'Department Clearance', order: 15, description: 'Plant tools, IT, Finance, & HR digital sign-offs' },
  { key: 'ff_settlement', label: 'Full & Final (F&F)', order: 16, description: 'Final dues, leave encashment & gratuity clearance' },
  { key: 'exit_documentation', label: 'Exit & Archival', order: 17, description: 'Relieving certificate & permanent statutory archival' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'usr_super_admin',
    name: 'Alexander Sterling',
    email: 'alexander.sterling@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    roles: ['super_admin'],
    activeRole: 'super_admin',
    status: 'active',
    lastLogin: '2026-08-14T08:45:00Z',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'usr_hr_admin',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    roles: ['hr_admin', 'reporting_manager'],
    activeRole: 'hr_admin',
    employeeId: 'emp_001',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-14T09:12:00Z',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'usr_hr_exec',
    name: 'Priya Sharma',
    email: 'priya.sharma@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    roles: ['hr_executive'],
    activeRole: 'hr_executive',
    employeeId: 'emp_002',
    departmentId: 'dept_hr',
    status: 'active',
    lastLogin: '2026-08-14T07:30:00Z',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'usr_payroll',
    name: 'Marcus Chen',
    email: 'marcus.chen@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    roles: ['payroll_officer'],
    activeRole: 'payroll_officer',
    employeeId: 'emp_003',
    departmentId: 'dept_fin',
    status: 'active',
    lastLogin: '2026-08-14T06:00:00Z',
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'usr_manager',
    name: 'Dr. Vikramaditya Rathore',
    email: 'vikram.rathore@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    roles: ['reporting_manager', 'employee'],
    activeRole: 'reporting_manager',
    employeeId: 'emp_004',
    departmentId: 'dept_qc',
    status: 'active',
    lastLogin: '2026-08-14T08:00:00Z',
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'usr_employee',
    name: 'Ananya Deshmukh',
    email: 'ananya.deshmukh@apexops.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    roles: ['employee'],
    activeRole: 'employee',
    employeeId: 'emp_005',
    departmentId: 'dept_qc',
    status: 'active',
    lastLogin: '2026-08-14T09:25:00Z',
    createdAt: '2025-03-01T00:00:00Z',
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dept_prod', name: 'Production & Manufacturing Ops', code: 'PMO', headName: 'Sarah Jenkins', employeeCount: 38 },
  { id: 'dept_qc', name: 'Quality Assurance & Analytical Lab', code: 'QAQC', headId: 'emp_004', headName: 'Dr. Vikramaditya Rathore', employeeCount: 16 },
  { id: 'dept_eng', name: 'Plant Engineering & Utilities', code: 'ENG', headName: 'Robert Miller', employeeCount: 14 },
  { id: 'dept_scm', name: 'Supply Chain & Material Logistics', code: 'SCM', headName: 'Rohan Mehra', employeeCount: 18 },
  { id: 'dept_ehs', name: 'Environmental Health & Safety (EHS)', code: 'EHS', headName: 'Amit Patel', employeeCount: 6 },
  { id: 'dept_hr', name: 'Human Resources & Industrial Relations', code: 'HRIR', headId: 'emp_001', headName: 'Eleanor Vance', employeeCount: 8 },
  { id: 'dept_fin', name: 'Finance, Costing & Accounts', code: 'FIN', headId: 'emp_003', headName: 'Marcus Chen', employeeCount: 8 },
];

export const MOCK_DESIGNATIONS: Designation[] = [
  { id: 'des_hr_dir', title: 'VP of Human Resources & IR', departmentId: 'dept_hr', grade: 'M7', level: 7 },
  { id: 'des_hr_exec', title: 'HR Operations & Compliance Officer', departmentId: 'dept_hr', grade: 'M3', level: 3 },
  { id: 'des_fin_lead', title: 'Principal Payroll & Plant Cost Lead', departmentId: 'dept_fin', grade: 'M5', level: 5 },
  { id: 'des_qc_dir', title: 'VP of Quality & Process Standards', departmentId: 'dept_qc', grade: 'M8', level: 8 },
  { id: 'des_qc_sr', title: 'Senior Analytical Chemist & QC Lead', departmentId: 'dept_qc', grade: 'M4', level: 4 },
  { id: 'des_prod_eng', title: 'Process & Batch Operations Engineer', departmentId: 'dept_prod', grade: 'M3', level: 3 },
  { id: 'des_qc_spec', title: 'Quality Control Specialist', departmentId: 'dept_qc', grade: 'M3', level: 3 },
];

export const MOCK_BRANCHES: Branch[] = [
  { id: 'br_blr', name: 'North Manufacturing Facility (Plant 1)', city: 'Bengaluru', country: 'India', isHeadquarters: true },
  { id: 'br_hyd', name: 'Central Industrial Complex (Plant 2)', city: 'Hyderabad', country: 'India', isHeadquarters: false },
  { id: 'br_mum', name: 'Corporate Commercial Office', city: 'Mumbai', country: 'India', isHeadquarters: false },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp_001',
    userId: 'usr_hr_admin',
    employeeCode: 'APX-1001',
    firstName: 'Eleanor',
    lastName: 'Vance',
    email: 'eleanor.vance@apexops.com',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1988-04-12',
    dateOfJoining: '2021-03-15',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Industrial Relations',
    designationId: 'des_hr_dir',
    designationTitle: 'VP of Human Resources & IR',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'active',
    currentLifecycleStage: 'compliance',
    ctc: 3200000,
    bankDetails: {
      accountNumber: '•••• •••• 9821',
      bankName: 'HDFC Bank Ltd',
      ifscCode: 'HDFC0001234',
      pan: 'ABCDE1234F',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1001',
      esiNumber: '53-00-123456-000-0001',
      uan: '100987654321',
    },
    emergencyContact: {
      name: 'Robert Vance',
      relationship: 'Spouse',
      phone: '+91 98765 43219',
    },
  },
  {
    id: 'emp_002',
    userId: 'usr_hr_exec',
    employeeCode: 'APX-1002',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@apexops.com',
    phone: '+91 98765 43211',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1995-09-24',
    dateOfJoining: '2023-06-01',
    departmentId: 'dept_hr',
    departmentName: 'Human Resources & Industrial Relations',
    designationId: 'des_hr_exec',
    designationTitle: 'HR Operations & Compliance Officer',
    reportingManagerId: 'emp_001',
    reportingManagerName: 'Eleanor Vance',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'active',
    currentLifecycleStage: 'training',
    ctc: 950000,
    bankDetails: {
      accountNumber: '•••• •••• 4412',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000987',
      pan: 'FGHIJ5678K',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1002',
      uan: '100987654322',
    },
    emergencyContact: {
      name: 'Rajesh Sharma',
      relationship: 'Father',
      phone: '+91 98765 43220',
    },
  },
  {
    id: 'emp_003',
    userId: 'usr_payroll',
    employeeCode: 'APX-1003',
    firstName: 'Marcus',
    lastName: 'Chen',
    email: 'marcus.chen@apexops.com',
    phone: '+91 98765 43212',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1990-11-05',
    dateOfJoining: '2022-01-10',
    departmentId: 'dept_fin',
    departmentName: 'Finance, Costing & Accounts',
    designationId: 'des_fin_lead',
    designationTitle: 'Principal Payroll & Plant Cost Lead',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'active',
    currentLifecycleStage: 'payroll',
    ctc: 2100000,
    bankDetails: {
      accountNumber: '•••• •••• 8820',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0000543',
      pan: 'KLMNO9012P',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1003',
      uan: '100987654323',
    },
    emergencyContact: {
      name: 'Linda Chen',
      relationship: 'Spouse',
      phone: '+91 98765 43221',
    },
  },
  {
    id: 'emp_004',
    userId: 'usr_manager',
    employeeCode: 'APX-1004',
    firstName: 'Dr. Vikramaditya',
    lastName: 'Rathore',
    email: 'vikram.rathore@apexops.com',
    phone: '+91 98765 43213',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1984-02-18',
    dateOfJoining: '2020-08-01',
    departmentId: 'dept_qc',
    departmentName: 'Quality Assurance & Analytical Lab',
    designationId: 'des_qc_dir',
    designationTitle: 'VP of Quality & Process Standards',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'active',
    currentLifecycleStage: 'performance',
    ctc: 4800000,
    bankDetails: {
      accountNumber: '•••• •••• 1109',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0004567',
      pan: 'PQRST3456U',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1004',
      uan: '100987654324',
    },
    emergencyContact: {
      name: 'Sunita Rathore',
      relationship: 'Spouse',
      phone: '+91 98765 43222',
    },
  },
  {
    id: 'emp_005',
    userId: 'usr_employee',
    employeeCode: 'APX-1005',
    firstName: 'Ananya',
    lastName: 'Deshmukh',
    email: 'ananya.deshmukh@apexops.com',
    phone: '+91 98765 43214',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1998-07-30',
    dateOfJoining: '2024-02-15',
    departmentId: 'dept_qc',
    departmentName: 'Quality Assurance & Analytical Lab',
    designationId: 'des_qc_sr',
    designationTitle: 'Senior Analytical Chemist & QC Lead',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'active',
    currentLifecycleStage: 'performance',
    ctc: 1850000,
    bankDetails: {
      accountNumber: '•••• •••• 6534',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0001122',
      pan: 'UVWXY7890Z',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1005',
      uan: '100987654325',
    },
    emergencyContact: {
      name: 'Sanjay Deshmukh',
      relationship: 'Father',
      phone: '+91 98765 43223',
    },
  },
  {
    id: 'emp_006',
    userId: 'usr_emp_006',
    employeeCode: 'APX-1006',
    firstName: 'Karthik',
    lastName: 'Subramanian',
    email: 'karthik.s@apexops.com',
    phone: '+91 98765 43215',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    gender: 'male',
    dob: '1996-03-14',
    dateOfJoining: '2024-06-10',
    departmentId: 'dept_prod',
    departmentName: 'Production & Manufacturing Ops',
    designationId: 'des_prod_eng',
    designationTitle: 'Process & Batch Operations Engineer',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_hyd',
    branchName: 'Central Industrial Complex (Plant 2)',
    employmentStatus: 'probation',
    currentLifecycleStage: 'onboarding',
    ctc: 1200000,
    bankDetails: {
      accountNumber: '•••• •••• 7712',
      bankName: 'HDFC Bank Ltd',
      ifscCode: 'HDFC0004455',
      pan: 'ZXCVB1234Q',
    },
    statutory: {
      pfNumber: 'TS/HYD/0098765/000/1006',
      uan: '100987654326',
    },
    emergencyContact: {
      name: 'Meena Subramanian',
      relationship: 'Mother',
      phone: '+91 98765 43224',
    },
  },
  {
    id: 'emp_007',
    userId: 'usr_emp_007',
    employeeCode: 'APX-1007',
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    email: 'sneha.k@apexops.com',
    phone: '+91 98765 43216',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    gender: 'female',
    dob: '1993-12-08',
    dateOfJoining: '2023-01-15',
    departmentId: 'dept_qc',
    departmentName: 'Quality Assurance & Analytical Lab',
    designationId: 'des_qc_spec',
    designationTitle: 'Quality Control Specialist',
    reportingManagerId: 'emp_004',
    reportingManagerName: 'Dr. Vikramaditya Rathore',
    branchId: 'br_blr',
    branchName: 'North Manufacturing Facility (Plant 1)',
    employmentStatus: 'notice_period',
    currentLifecycleStage: 'resignation',
    ctc: 1650000,
    bankDetails: {
      accountNumber: '•••• •••• 9931',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001928',
      pan: 'ASDFG5678H',
    },
    statutory: {
      pfNumber: 'KN/BNG/0098765/000/1007',
      uan: '100987654327',
    },
    emergencyContact: {
      name: 'Amit Kulkarni',
      relationship: 'Spouse',
      phone: '+91 98765 43225',
    },
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att_1', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-14', inTime: '08:30 AM', outTime: '05:30 PM', totalHours: 9.00, status: 'present', source: 'biometric' },
  { id: 'att_2', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-13', inTime: '08:25 AM', outTime: '05:40 PM', totalHours: 9.25, status: 'present', source: 'biometric' },
  { id: 'att_3', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-12', inTime: '09:45 AM', outTime: '06:00 PM', totalHours: 8.25, status: 'present', source: 'manual', regularizationStatus: 'approved', regularizationReason: 'Plant gate pass transit verification' },
  { id: 'att_4', employeeId: 'emp_005', employeeName: 'Ananya Deshmukh', date: '2026-08-11', inTime: '08:30 AM', outTime: '01:00 PM', totalHours: 4.50, status: 'half_day', source: 'web_checkin' },
  { id: 'att_5', employeeId: 'emp_006', employeeName: 'Karthik Subramanian', date: '2026-08-14', inTime: '08:00 AM', outTime: '05:00 PM', totalHours: 9.00, status: 'present', source: 'biometric' },
  { id: 'att_6', employeeId: 'emp_007', employeeName: 'Sneha Kulkarni', date: '2026-08-14', inTime: '08:45 AM', outTime: '05:45 PM', totalHours: 9.00, status: 'present', source: 'biometric' },
  { id: 'att_7', employeeId: 'emp_002', employeeName: 'Priya Sharma', date: '2026-08-14', inTime: '09:00 AM', outTime: '06:00 PM', totalHours: 9.00, status: 'present', source: 'biometric' },
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr_101',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    leaveType: 'casual',
    fromDate: '2026-08-20',
    toDate: '2026-08-21',
    daysCount: 2,
    reason: 'Family wedding ceremony out of town',
    status: 'pending',
    approverId: 'emp_004',
    approverName: 'Dr. Vikramaditya Rathore',
    appliedAt: '2026-08-13T14:30:00Z',
  },
  {
    id: 'lr_102',
    employeeId: 'emp_006',
    employeeName: 'Karthik Subramanian',
    leaveType: 'sick',
    fromDate: '2026-08-05',
    toDate: '2026-08-05',
    daysCount: 1,
    reason: 'Seasonal fever and medical checkup',
    status: 'approved',
    approverId: 'emp_004',
    approverName: 'Dr. Vikramaditya Rathore',
    appliedAt: '2026-08-04T20:15:00Z',
    approverComment: 'Approved. Take rest and recover.',
  },
  {
    id: 'lr_103',
    employeeId: 'emp_002',
    employeeName: 'Priya Sharma',
    leaveType: 'earned',
    fromDate: '2026-09-01',
    toDate: '2026-09-05',
    daysCount: 5,
    reason: 'Annual planned leave',
    status: 'approved',
    approverId: 'emp_001',
    approverName: 'Eleanor Vance',
    appliedAt: '2026-08-10T10:00:00Z',
    approverComment: 'Approved.',
  },
];

export const MOCK_LEAVE_BALANCES: LeaveBalance[] = [
  { employeeId: 'emp_005', leaveType: 'casual', totalAllocated: 12, used: 3, pending: 2, balance: 7 },
  { employeeId: 'emp_005', leaveType: 'sick', totalAllocated: 10, used: 2, pending: 0, balance: 8 },
  { employeeId: 'emp_005', leaveType: 'earned', totalAllocated: 15, used: 4, pending: 0, balance: 11 },
  { employeeId: 'emp_005', leaveType: 'maternity', totalAllocated: 180, used: 0, pending: 0, balance: 180 },
];

export const MOCK_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: 'pr_2026_07',
    period: '2026-07',
    monthName: 'July',
    year: 2026,
    status: 'disbursed',
    totalEmployees: 108,
    totalGrossPay: 7850000,
    totalDeductions: 1140000,
    totalNetPay: 6710000,
    varianceCount: 0,
    runDate: '2026-07-31T18:00:00Z',
    approvedBy: 'Eleanor Vance',
    approvedAt: '2026-07-31T17:30:00Z',
  },
  {
    id: 'pr_2026_08',
    period: '2026-08',
    monthName: 'August',
    year: 2026,
    status: 'under_review',
    totalEmployees: 110,
    totalGrossPay: 8120000,
    totalDeductions: 1180000,
    totalNetPay: 6940000,
    varianceCount: 3,
    runDate: '2026-08-14T11:00:00Z',
  },
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'ps_2026_07_005',
    payrollRunId: 'pr_2026_07',
    employeeId: 'emp_005',
    employeeCode: 'APX-1005',
    employeeName: 'Ananya Deshmukh',
    designation: 'Senior Analytical Chemist & QC Lead',
    department: 'Quality Assurance & Analytical Lab',
    period: 'July 2026',
    paidDays: 31,
    lopDays: 0,
    breakup: calculateSalaryBreakup(1850000),
    paymentMode: 'bank_transfer',
    status: 'published',
  },
  {
    id: 'ps_2026_07_006',
    payrollRunId: 'pr_2026_07',
    employeeId: 'emp_006',
    employeeCode: 'APX-1006',
    employeeName: 'Karthik Subramanian',
    designation: 'Process & Batch Operations Engineer',
    department: 'Production & Manufacturing Ops',
    period: 'July 2026',
    paidDays: 31,
    lopDays: 0,
    breakup: calculateSalaryBreakup(1200000),
    paymentMode: 'bank_transfer',
    status: 'published',
  },
];

export const MOCK_REQUISITIONS: ManpowerRequisition[] = [
  {
    id: 'req_001',
    departmentId: 'dept_qc',
    departmentName: 'Quality Assurance & Analytical Lab',
    positionTitle: 'Lead Process Quality Chemist & SOP Auditor',
    openingsCount: 2,
    urgency: 'high',
    requestedById: 'emp_004',
    requestedByName: 'Dr. Vikramaditya Rathore',
    status: 'approved',
    targetDate: '2026-09-30',
    minExperience: '6+ Years',
    justification: 'Scaling batch testing, HPLC analytical workflows, and ISO 9001 compliance standards for Plant Unit 2.',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'req_002',
    departmentId: 'dept_prod',
    departmentName: 'Production & Manufacturing Ops',
    positionTitle: 'Senior Shift Manufacturing Supervisor',
    openingsCount: 1,
    urgency: 'medium',
    requestedById: 'emp_001',
    requestedByName: 'Eleanor Vance',
    status: 'in_progress',
    targetDate: '2026-09-15',
    minExperience: '5+ Years',
    justification: 'Continuous production shift supervision and safety compliance oversight.',
    createdAt: '2026-08-05T11:00:00Z',
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand_01',
    requisitionId: 'req_001',
    name: 'Devraj Mukherjee',
    email: 'devraj.mukherjee@example.com',
    phone: '+91 98111 22334',
    position: 'Lead Process Quality Chemist',
    department: 'Quality Assurance & Analytical Lab',
    experienceYears: 8,
    currentStage: 'interview',
    score: 94,
    interviewDate: '2026-08-14T11:00:00Z',
    interviewerId: 'emp_004',
    interviewerName: 'Dr. Vikramaditya Rathore',
    interviewerScorecard: {
      technicalRating: 4.9,
      cultureRating: 4.6,
      communicationRating: 4.7,
      comments: 'Thorough expertise in analytical instrumentation, batch yield optimization, QA protocols, and industrial safety.',
      recommendation: 'hire',
    },
  },
  {
    id: 'cand_02',
    requisitionId: 'req_001',
    name: 'Shreya Sengupta',
    email: 'shreya.sengupta@example.com',
    phone: '+91 98222 33445',
    position: 'Lead Process Quality Chemist',
    department: 'Quality Assurance & Analytical Lab',
    experienceYears: 7,
    currentStage: 'offered',
    score: 89,
    offerDetails: {
      offeredCtc: 2400000,
      joiningDate: '2026-09-15',
      status: 'sent',
    },
  },
  {
    id: 'cand_03',
    requisitionId: 'req_001',
    name: 'Nikhil Verma',
    email: 'nikhil.verma@example.com',
    phone: '+91 98333 44556',
    position: 'Lead Process Quality Chemist',
    department: 'Quality Assurance & Analytical Lab',
    experienceYears: 6,
    currentStage: 'screened',
    score: 85,
  },
  {
    id: 'cand_04',
    requisitionId: 'req_001',
    name: 'Aarav Patel',
    email: 'aarav.patel@example.com',
    phone: '+91 98444 55667',
    position: 'Lead Process Quality Chemist',
    department: 'Quality Assurance & Analytical Lab',
    experienceYears: 5,
    currentStage: 'applied',
    score: 78,
  },
];

export const MOCK_PERFORMANCE_CYCLES: PerformanceCycle[] = [
  {
    id: 'pc_2025_26',
    title: 'Annual Plant & Operational Performance Appraisal FY26',
    period: 'FY 2025-2026',
    status: 'calibration',
    deadline: '2026-08-30',
    totalEligible: 104,
    submittedCount: 99,
    reviewedCount: 92,
  },
];

export const MOCK_PERFORMANCE_REVIEWS: PerformanceReview[] = [
  {
    id: 'pr_rev_005',
    cycleId: 'pc_2025_26',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    department: 'Quality Assurance & Analytical Lab',
    designation: 'Senior Analytical Chemist & QC Lead',
    kras: [
      { title: 'Quality Assurance & Analytical Accuracy', weightage: 35, target: 'Maintain 99.8% precision in batch quality releases and zero defect returns', selfScore: 4.9, managerScore: 4.8 },
      { title: 'EHS & Plant Safety Compliance', weightage: 25, target: '100% adherence to hazardous material handling and safety audit checks', selfScore: 4.8, managerScore: 4.8 },
      { title: 'SOP Documentation & Training', weightage: 20, target: 'Update 12 plant standard operating procedures and train junior technicians', selfScore: 4.6, managerScore: 4.6 },
      { title: 'Testing Cycle Time Reduction', weightage: 20, target: 'Reduce sample testing turnaround time by 15% through workflow streamlining', selfScore: 4.7, managerScore: 4.7 },
    ],
    selfRating: 4.78,
    managerRating: 4.74,
    finalRating: 4.75,
    managerComments: 'Ananya has delivered stellar precision across batch quality audits, upholding rigorous ISO and plant safety benchmarks.',
    hrCalibrationNotes: 'Top-tier performer. Recommended for Lead Quality Specialist promotion with merit increment.',
    recommendation: 'promotion',
    status: 'in_calibration',
  },
];

export const MOCK_GRIEVANCES: GrievanceTicket[] = [
  {
    id: 'grv_01',
    ticketNumber: 'GRV-2026-0042',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    isAnonymous: false,
    category: 'work_environment',
    subject: 'Safety ventilation and exhaust maintenance in Lab Block B',
    description: 'Fume hood exhaust ventilation airflow needs scheduled filter servicing and calibration.',
    priority: 'medium',
    status: 'under_investigation',
    slaDeadline: '2026-08-18T18:00:00Z',
    assignedToName: 'Robert Miller (Plant Maintenance)',
    createdAt: '2026-08-11T10:00:00Z',
  },
  {
    id: 'grv_02',
    ticketNumber: 'GRV-2026-0043',
    isAnonymous: true,
    category: 'policy_violation',
    subject: 'Night shift transportation and meal timing coordination',
    description: 'Request for scheduled bus transport timing alignment with 10:00 PM shift changeover.',
    priority: 'high',
    status: 'resolved',
    slaDeadline: '2026-08-14T18:00:00Z',
    assignedToName: 'Eleanor Vance (HR)',
    resolutionNotes: 'Coordinated with transport vendor; evening route revised to align exactly with plant shift transitions.',
    createdAt: '2026-08-08T15:30:00Z',
  },
];

export const MOCK_TRAININGS: TrainingProgram[] = [
  {
    id: 'trn_01',
    title: 'Industrial Safety, Hazardous Material & PPE Standards',
    trainer: 'National Safety Council Lead Auditors (External)',
    category: 'compliance',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    mode: 'external_vendor',
    vendorName: 'National Industrial Safety Institute',
    capacity: 35,
    enrolledCount: 30,
    status: 'upcoming',
  },
  {
    id: 'trn_02',
    title: 'ISO 9001:2015 Quality & Standard Operating Procedure Workshop',
    trainer: 'Dr. Vikramaditya Rathore & QA Team',
    category: 'technical',
    startDate: '2026-08-10',
    endDate: '2026-08-10',
    mode: 'internal',
    capacity: 80,
    enrolledCount: 76,
    status: 'completed',
    feedbackAvgScore: 4.88,
  },
];

export const MOCK_POLICIES: PolicyDocument[] = [
  {
    id: 'pol_01',
    title: 'Plant Safety, Industrial Protocols & Mandatory PPE Policy',
    category: 'it_security',
    version: 'v4.1',
    effectiveDate: '2026-01-01',
    acknowledgedCount: 106,
    totalEmployees: 108,
    fileUrl: '/policies/industrial-safety-policy.pdf',
  },
  {
    id: 'pol_02',
    title: 'Code of Business Conduct & Operational Integrity',
    category: 'code_of_conduct',
    version: 'v3.2',
    effectiveDate: '2026-01-01',
    acknowledgedCount: 108,
    totalEmployees: 108,
    fileUrl: '/policies/code-of-conduct.pdf',
  },
  {
    id: 'pol_03',
    title: 'Prevention of Sexual Harassment (POSH) Policy 2026',
    category: 'posh',
    version: 'v5.0',
    effectiveDate: '2026-01-01',
    acknowledgedCount: 108,
    totalEmployees: 108,
    fileUrl: '/policies/posh-policy.pdf',
  },
];

export const MOCK_RESIGNATIONS: ResignationCase[] = [
  {
    id: 'res_001',
    employeeId: 'emp_007',
    employeeName: 'Sneha Kulkarni',
    resignationDate: '2026-07-20',
    requestedLwd: '2026-08-20',
    approvedLwd: '2026-08-20',
    noticePeriodDays: 30,
    reason: 'Higher education and specialized post-graduate studies',
    status: 'clearance_in_progress',
    clearances: {
      it: { status: 'cleared', clearedBy: 'IT Admin Team', notes: 'System access revoked & laptop returned.' },
      admin: { status: 'cleared', clearedBy: 'Plant Admin', notes: 'Locker cleared and safety gear deposited.' },
      finance: { status: 'pending', notes: 'Travel claim audit under final approval.' },
      hr: { status: 'pending', notes: 'Exit interview scheduled for Aug 18.' },
    },
    ffSettlement: {
      pendingSalary: 95400,
      leaveEncashment: 38200,
      bonusGratuity: 0,
      noticeShortfallDeduction: 0,
      assetDeduction: 0,
      totalNetSettlement: 133600,
      status: 'draft',
    },
  },
];

export const MOCK_DISCIPLINARY: DisciplinaryCase[] = [
  {
    id: 'disc_01',
    caseNumber: 'DISC-2026-003',
    employeeId: 'emp_006',
    employeeName: 'Karthik Subramanian',
    violationType: 'absenteeism',
    incidentDate: '2026-07-15',
    reportedBy: 'Dr. Vikramaditya Rathore',
    severity: 'minor',
    currentStage: 'capa_active',
    actionTaken: 'written_warning',
    createdAt: '2026-07-16T14:00:00Z',
  },
];

export const MOCK_TRANSFERS: TransferPromotionCase[] = [
  {
    id: 'tp_01',
    employeeId: 'emp_005',
    employeeName: 'Ananya Deshmukh',
    type: 'promotion',
    currentDepartment: 'Quality Assurance & Analytical Lab',
    newDepartment: 'Quality Assurance & Analytical Lab',
    currentDesignation: 'Senior Analytical Chemist & QC Lead',
    newDesignation: 'Principal Quality Assurance Specialist',
    currentBranch: 'North Manufacturing Facility (Plant 1)',
    newBranch: 'North Manufacturing Facility (Plant 1)',
    effectiveDate: '2026-09-01',
    initiatedBy: 'Dr. Vikramaditya Rathore',
    status: 'pending_approval',
    approvalChain: ['Dr. Vikramaditya Rathore (Dept Head)', 'Eleanor Vance (HR VP)'],
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  { id: 'aud_1', userId: 'usr_hr_admin', userName: 'Eleanor Vance', role: 'hr_admin', action: 'APPROVED_REQUISITION', module: 'recruitment', entityId: 'req_001', details: 'Approved Lead Process Quality Chemist position for QA Lab', timestamp: '2026-08-14T09:40:12Z', ipAddress: '10.0.4.18' },
  { id: 'aud_2', userId: 'usr_payroll', userName: 'Marcus Chen', role: 'payroll_officer', action: 'INITIATED_PAYROLL_RUN', module: 'payroll_benefits', entityId: 'pr_2026_08', details: 'Generated August 2026 payroll input sheet for 110 employees', timestamp: '2026-08-14T06:00:00Z', ipAddress: '10.0.2.44' },
  { id: 'aud_3', userId: 'usr_manager', userName: 'Dr. Vikramaditya Rathore', role: 'reporting_manager', action: 'SUBMITTED_SCORECARD', module: 'recruitment', entityId: 'cand_01', details: 'Submitted 4.9/5.0 interview scorecard for Devraj Mukherjee', timestamp: '2026-08-13T16:15:30Z', ipAddress: '10.0.1.92' },
  { id: 'aud_4', userId: 'usr_super_admin', userName: 'Alexander Sterling', role: 'super_admin', action: 'UPDATED_SECURITY_POLICY', module: 'system_settings', entityId: 'sec_01', details: 'Configured role permissions and enforced mandatory audit logging', timestamp: '2026-08-10T11:00:00Z', ipAddress: '10.0.0.1' },
];

export const MOCK_NOTIFICATIONS: SystemNotification[] = [
  { id: 'notif_1', title: 'New Leave Request', message: 'Ananya Deshmukh applied for 2 days Casual Leave (20-21 Aug)', type: 'info', module: 'attendance_leave', createdAt: '2026-08-13T14:30:00Z', read: false, link: '/leaves' },
  { id: 'notif_2', title: 'August Payroll Review', message: 'August 2026 Payroll Run is ready for HR Admin approval', type: 'warning', module: 'payroll_benefits', createdAt: '2026-08-14T11:05:00Z', read: false, link: '/payroll' },
  { id: 'notif_3', title: 'Candidate Scorecard', message: 'Scorecard submitted for Devraj Mukherjee (Quality Chemist)', type: 'success', module: 'recruitment', createdAt: '2026-08-13T16:20:00Z', read: true, link: '/recruitment' },
  { id: 'notif_4', title: 'EHS Training Scheduled', message: 'Industrial Safety & Hazardous Material training opens Aug 22', type: 'info', module: 'training_dev', createdAt: '2026-08-12T09:00:00Z', read: false, link: '/training' },
];
